<<<<<<< HEAD
version: '3.5'
=======
version: '3.1'
>>>>>>> b8f188b (增加PIR相关应用)

services:
  db:
    image: "postgres:alpine"
    environment:
<<<<<<< HEAD
      - POSTGRES_USER={{project_name}}
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB={{project_name}}
=======
      - POSTGRES_USER=privacy_computing_demo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=privacy_computing_demo
>>>>>>> b8f188b (增加PIR相关应用)
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result
      - frontend

  celery:
    build:
      dockerfile: backend/Dockerfile
      context: .
    command: python manage.py celery
    volumes:
<<<<<<< HEAD
      - ./:/home/user/app/
=======
      - ./backend/:/home/user/app/
>>>>>>> b8f188b (增加PIR相关应用)
    env_file: backend/.env
    depends_on:
      - db
      - broker
      - result

  mailhog: # service for faking a SMTP server
    image: mailhog/mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui

volumes:
  dbdata:
<<<<<<< HEAD
    name: {{project_name}}_dbdata
    external: true
=======
    external:
      name: privacy_computing_demo_dbdata
>>>>>>> b8f188b (增加PIR相关应用)
